name: Update Last Updated Date

on:
  push:
    branches:
      - main  # Change this if your default branch is different (e.g., gh-pages or master)

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get last commit date
        run: |
          echo "{\"lastUpdated\": \"$(git log -1 --format=%cd --date=format:'%d.%m.%Y')\"}" > meta.json

      - name: Debug print meta.json
        run: cat meta.json

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add meta.json
          git diff --cached --quiet || git commit -m "Update last updated date"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
